spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    jdbcUrl: jdbc:postgresql://localhost:5432/challengeproject
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver